%TEST_COMPONENT_BRACHISTOCHRONE Brachistochrone / Bead Descent problem 
%   TEST_COMPONENT_BRACHISTOCHRONE uses a discretized version of the bead 
%   descent problem to test the computation of component solution spaces.
%   First, the analytical curve of least time (brachistochrone) is computed, 
%   followed by the box-shaped solution space (with a requirement around the 
%   time it takes for the slide from A to B happen) and the component solution 
%   spaces. The results are compared after all computations are done. 
%
%   Copyright 2025 Eduardo Rodrigues Della Noce
%   SPDX-License-Identifier: Apache-2.0

%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
%   
%       http://www.apache.org/licenses/LICENSE-2.0
%   
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.


%% cleanup
close all;
fclose all;
clear all;
more off;
diary off;
clc;


%% debugging
rng(4);


%% Documentation / Archive
RNGstate = rng;
saveFolder = save_diary_files(mfilename);
goldenRatio = (1+sqrt(5))/2;
figureSize = [goldenRatio 1]*8.5;


%% setup problem parameters
nDivision = 15; % number of design variables (discritization)
initialDistanceWidth = 4; % distance in longitudinal (x) direction
initialDistanceHeight = 2; % distance in vertical (y) direction
nInterpolationPoint = 5000; % number of interpolation points


%% Problem Setup
systemFunction = @bead_slide_time;
systemParameter(1) = initialDistanceWidth; % distance in longitudinal (x) direction
systemParameter(2) = initialDistanceHeight; % distance in vertical (y) direction
systemParameter(3) = nInterpolationPoint; % number of interpolation points

designSpaceLowerBound = -initialDistanceHeight*ones(1,nDivision);
designSpaceUpperBound = initialDistanceHeight*ones(1,nDivision);


%% Run Initial Optimization (Find Optimal Time)
% initial guess - linear interpolation
initialDesign = linspace(initialDistanceHeight,0,nDivision+2); % in initial interpolation consider end-points... 
initialDesign = initialDesign(2:end-1); % ... which are then removed
pathWidthDivision = linspace(0,initialDistanceWidth,nDivision+2);

% run optimization
bottomUpMapping = BottomUpMappingFunction(systemFunction,systemParameter);
[designOptimal,timeOptimal,optimizationOutput,systemResponseData] = design_optimize_quantities_of_interest(...
    bottomUpMapping,...
    initialDesign,...
    designSpaceLowerBound,...
    designSpaceUpperBound,...
    @(performanceMeasure)performanceMeasure,...
    'OptimizationMethodOptions',{'Display','iter-detailed'});
referenceTime = bottomUpMapping.response(initialDesign);


%% Solve  Problem Analytically (Reference)
radiusAngleOptimal = fsolve(@(rt)brachistochrone_solve_analytical(rt,systemParameter),[1 1]);
anglePathAnalytical = linspace(0,radiusAngleOptimal(2),nInterpolationPoint);
pathWidthAnalytical = radiusAngleOptimal(1)*(anglePathAnalytical-sin(anglePathAnalytical));
pathHeightAnalytical = radiusAngleOptimal(1)*(-1+cos(anglePathAnalytical)) + initialDistanceHeight;


%% Perform Solution Space Computation
performanceLowerLimit = -inf;
performanceUpperLimit = referenceTime;

optionsBox = sso_stochastic_options('box',...
    'UseAdaptiveGrowthRate',true,...
    'NumberSamplesPerIteration',100,...
    'GrowthRate',0.005,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',200,...
    'MaxIterConsolidation',200,...
    'TrimmingOperationOptions',{'PassesCriterion','reduced'},...
    'TrimmingOrderOptions',{'OrderPreference','score'},...
    'LoggingLevel','all');

designEvaluator = DesignEvaluatorBottomUpMapping(bottomUpMapping,performanceLowerLimit,performanceUpperLimit);
[designBoxOptimal,problemDataBox,iterDataBox] = sso_box_stochastic(designEvaluator,...
    designOptimal,designSpaceLowerBound,designSpaceUpperBound,optionsBox);


%% plot
figure; 
hold on;
for i=1:nDivision
    handleSolutionSpacePlot = plot([pathWidthDivision(i+1) pathWidthDivision(i+1)],designBoxOptimal(:,i),'g-','linewidth',12);
end
handleNumericalOptimal = plot(pathWidthDivision,[initialDistanceHeight,designOptimal,0]','bo-','linewidth',1);
plot([0 systemParameter(1)],[0 0],'k--');
handleBrachistochrone = plot(pathWidthAnalytical,pathHeightAnalytical,'r','linewidth',1);
grid minor;
xlim([0 systemParameter(1)])
title(sprintf('Approximate Optimal Time: %gs | Time Requirement: %gs',...
    timeOptimal,performanceUpperLimit));
xlabel('Longitudinal Distance [m]');
ylabel('Vertical Distance [m]');
legend([handleSolutionSpacePlot handleNumericalOptimal handleBrachistochrone],{'Solution Spaces', ...
    'Numerical Optimal Solution','Analytical Optimal Solution'})


%% same problem, component solution spaces - planar trimming
options = sso_stochastic_options('component',...
    'UseAdaptiveGrowthRate',true,...
    'TargetAcceptedRatioExploration',0.7,...
    'GrowthRate',0.005,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',200,...
    'MaxIterConsolidation',200,...
    'NumberSamplesPerIteration',100,...
    'CandidateSpaceConstructor',@CandidateSpaceConvexHull,...
    'TrimmingMethodFunction',@component_trimming_method_planar_trimming,...
    'UsePaddingSamplesInTrimming',true,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'ApplyLeanness','never',...
    'LoggingLevel','all',...
    'TrimmingOperationOptions',{'PassesCriterion','reduced'},...
    'TrimmingOrderOptions',{'OrderPreference','score'});

componentIndex = {1:3,4:6,7:9,10:12,13:15};
        
[planarTrimmingSolutionSpace,problemDataPlanarTrimming,iterDataPlanarTrimming] = sso_component_stochastic(designEvaluator,...
    designOptimal,designSpaceLowerBound,designSpaceUpperBound,componentIndex,options);


%% same problem, component solution spaces - corner box removal
options = sso_stochastic_options('component',...
    'UseAdaptiveGrowthRate',true,...
    'TargetAcceptedRatioExploration',0.7,...
    'GrowthRate',0.005,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',200,...
    'MaxIterConsolidation',200,...
    'NumberSamplesPerIteration',100,...
    'CandidateSpaceConstructor',@CandidateSpaceCornerBoxRemoval,...
    'TrimmingMethodFunction',@component_trimming_method_corner_box_removal,...
    ... 'TrimmingMethodOptions',{'CornersToTest','away'},...
    'UsePaddingSamplesInTrimming',true,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'ApplyLeanness','never',...
    'LoggingLevel','all',...
    'TrimmingOperationOptions',{'PassesCriterion','reduced'},...
    'TrimmingOrderOptions',{'OrderPreference','score'},...
    'MaximumGrowthAdaptationFactor',1.0);

componentIndex = {1:3,4:6,7:9,10:12,13:15};
        
[cornerBoxRemovalSolutionSpace,problemDataCornerBoxRemoval,iterDataCornerBoxRemoval] = sso_component_stochastic(designEvaluator,...
    designOptimal,designSpaceLowerBound,designSpaceUpperBound,componentIndex,options);


%% visualization
for i=1:size(componentIndex,2)
    currentBox = designBoxOptimal(:,componentIndex{i});
    currentComponentSpace = planarTrimmingSolutionSpace(i);
    
    figure;
    hold on;
    plot_design_box_3d(gcf,currentBox,'FaceAlpha',0.5,'FaceColor',[0.8 0.8 0.8]);
    planarTrimmingSolutionSpace(i).plot_candidate_space(gcf,...
        'FaceColor','green','EdgeColor','green','FaceAlpha',0.1);
    cornerBoxRemovalSolutionSpace(i).plot_candidate_space(gcf,...
        'FaceColor','blue','EdgeColor','blue','FaceAlpha',0.1);
    grid minor;
    

    %
    muBox(i) = prod(currentBox(2,:)-currentBox(1,:));
    
    %
    muComponent(i) = planarTrimmingSolutionSpace(i).Measure;
    muCornerBoxRemoval(i) = cornerBoxRemovalSolutionSpace(i).Measure;

    %
    title(sprintf('Box Volume = %gm^3 ; Planar Trimming Volume = %gm^3 ; Corner Box Removal Volume = %gm^3 ;',...
            muBox(i),muComponent(i),muCornerBoxRemoval(i)));
end

fprintf('\nTotal Box Volume: %g\nTotal Component Volume (Planar): %g\nTotal Component Volume (Corner): %g\nTotal Increase (Planar): %gx\nTotal Increase (Corner): %gx\n',...
    prod(muBox),prod(muComponent),prod(muCornerBoxRemoval),...
    prod(muComponent)/prod(muBox),prod(muCornerBoxRemoval)/prod(muBox));


%% performance metrics
resultsFolder = [saveFolder,sprintf('ResultsBox/')];
mkdir(resultsFolder);
algoDataBox = postprocess_sso_box_stochastic(problemDataBox,iterDataBox);
plot_sso_box_stochastic_metrics(algoDataBox,...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});

resultsFolder = [saveFolder,sprintf('ResultsPlanarTrimming/')];
mkdir(resultsFolder);
algoDataPlanarTrimming = postprocess_sso_component_stochastic(problemDataPlanarTrimming,iterDataPlanarTrimming);
plot_sso_component_stochastic_metrics(algoDataPlanarTrimming,...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});

resultsFolder = [saveFolder,sprintf('ResultsCornerBoxRemoval/')];
mkdir(resultsFolder);
algoDataCornerBoxRemoval = postprocess_sso_component_stochastic(problemDataCornerBoxRemoval,iterDataCornerBoxRemoval);
plot_sso_component_stochastic_metrics(algoDataCornerBoxRemoval,...
    'SaveFolder',saveFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});

resultsFolder = [saveFolder,sprintf('ResultsComparison/')];
mkdir(resultsFolder);
plot_sso_comparison_box_component_stochastic_metrics(...
    {algoDataBox},...
    {algoDataPlanarTrimming,algoDataCornerBoxRemoval},...
    'ComponentLabel',{'Planar Trimming','Corner Box Removal'},...
    'BoxColor','k',...
    'ComponentColor',color_palette_tol({'green','blue'}),...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',false,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});



%% Save and Stop Transcripting
save([saveFolder,'Data.mat']);
diary off;

