%test_component_hollow_sphere Component solution spaces for a sphere problem 
%   test_component_hollow_sphere computes a component solution spaces with 
%   for a sphere problem.
%
%   Copyright 2024 Eduardo Rodrigues Della Noce
%   SPDX-License-Identifier: Apache-2.0

%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
%   
%       http://www.apache.org/licenses/LICENSE-2.0
%   
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.


%% Cleanup
fclose all;
close all;
clear all;
clc;
more off;
diary off;


%% debugging
rng(4);


%% Documentation / Archive
rngState = rng;
saveFolder = save_diary_files(mfilename);
goldenRatio = (1+sqrt(5))/2;
figureSize = [goldenRatio 1]*8.5;


%% function call
%
systemFunction = @truss_six_bar_2d_two_moving_node;
systemParameter = [10,210e3,7850e-9]; % [mm^2],[MPa],[kg/mm^3]
%                                     x1   y1  x2  y2
designSpaceLowerBoundDisplacement = [0.1 -0.5 0.9 0.5];
designSpaceUpperBoundDisplacement = [1.5  0.5 2.0 1.5];
designSpaceLowerBoundMass = [0 -0.5 0 -0.5];
designSpaceUpperBoundMass = [2  1.5 2  1.5];
Components = {[1,2]',[3,4]'};
%
performanceLowerLimit = -inf;
performanceUpperLimit = [nan nan repmat(inf,1,6)];
%
initialDesign = [1,0,1,1];


%% find optimum
bottomUpMapping = BottomUpMappingFunction(systemFunction,systemParameter);

[nodePositionOptimalDisplacement,displacementOptimal] = design_optimize_quantities_of_interest(...
    bottomUpMapping,...
    initialDesign,...
    designSpaceLowerBoundDisplacement,...
    designSpaceUpperBoundDisplacement,...
    @(performanceMeasure)[performanceMeasure(1)],...
    ...'InequalityConstraintFunction',@(performanceMeasure)[performanceMeasure(3:end)-performanceUpperLimit(3:end)],...
    'OptimizationMethodFunction',@optimization_ga_wrapper,...
    'OptimizationMethodOptions',{'Display','diagnose'});

warning('off');
[nodePositionOptimalMass,massOptimal] = design_optimize_quantities_of_interest(...
    bottomUpMapping,...
    initialDesign,...
    designSpaceLowerBoundMass,...
    designSpaceUpperBoundMass,...
    @(performanceMeasure)[performanceMeasure(2)],...
    ...'InequalityConstraintFunction',@(performanceMeasure)[performanceMeasure(3:end)-performanceUpperLimit(3:end)],...
    'OptimizationMethodFunction',@optimization_ga_wrapper,...
    'OptimizationMethodOptions',{'Display','diagnose'});
warning('on');


%% plot optimum and deformations
baseNode = [...
    0 0;  ...
    nan nan; ...
    2 0.5; ...
    nan nan; ...
    0 1];
fixedDegreesOfFreedom = [...
    true true; ...
    false false; ...
    false false; ...
    false false; ...
    true true];
nodeForce = [...
    0 0; ...
    0 0; ...
    0 -1000; ...
    0 0; ...
    0 0];
nodeElement = [...
    1 2; ...
    2 3; ...
    3 4; ...
    4 5; ...
    2 5; ...
    2 4];
elementCrossSectionArea = systemParameter(1); % [mm^2]
elementYoungsModulus = systemParameter(2); % [MPa]

% initial truss
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign);
save_print_figure(gcf,[saveFolder,'InitialTruss']);

% initial truss + optimized truss
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTruss']);

% initial truss + optimized displacment truss + optimized mass truss
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'NodePositionOptimalMass',nodePositionOptimalMass);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussWithMass']);


% deformed trusses
nodePositionInitial = baseNode;
nodePositionInitial(2,:) = initialDesign(:,[1,2]);
nodePositionInitial(4,:) = initialDesign(:,[3,4]);
nodeDisplacementInitial = ...
	truss_analysis(...
		nodePositionInitial,...
		fixedDegreesOfFreedom,...
		nodeForce,...
		nodeElement,...
		elementCrossSectionArea,...
		elementYoungsModulus);

nodePositionOptimized = baseNode;
nodePositionOptimized(2,:) = nodePositionOptimalDisplacement(:,[1,2]);
nodePositionOptimized(4,:) = nodePositionOptimalDisplacement(:,[3,4]);
nodeDisplacementOptimal = ...
    truss_analysis(...
	    nodePositionOptimized,...
	    fixedDegreesOfFreedom,...
	    nodeForce,...
	    nodeElement,...
	    elementCrossSectionArea,...
	    elementYoungsModulus);

plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'DeformationInitial',nodeDisplacementInitial,...
    'DeformationOptimalDisplacement',nodeDisplacementOptimal);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussDeformation']);


%% establish upper performance limits
% update uppwer limit based on either optimal value or initial value
performanceMeasureInitial = bottomUpMapping.response(initialDesign);
performanceUpperLimitDisplacement = performanceUpperLimit;
performanceUpperLimitMass = performanceUpperLimit;

% displacement
performanceUpperLimitDisplacement(1) = performanceMeasureInitial(1);
designEvaluatorDisplacement = DesignEvaluatorBottomUpMapping(...
    bottomUpMapping,...
    performanceLowerLimit,...
    performanceUpperLimitDisplacement);

% mass
performanceUpperLimitMass(2) = performanceMeasureInitial(2);
designEvaluatorMass = DesignEvaluatorBottomUpMapping(...
    bottomUpMapping,...
    performanceLowerLimit,...
    performanceUpperLimitMass);


%% Box Opt
timeElapsedBox = tic;
optionsBox = sso_stochastic_options('box',...
    'NumberSamplesPerIterationExploration',300,...
    'NumberSamplesPerIterationConsolidation',300,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',30,...
    'MaxIterConsolidation',30,...
    'UseAdaptiveGrowthRate',false,...
    'GrowthRate',0.2,...
    'ApplyLeanness','never',...
    'TrimmingOperationOptions',{'PassesCriterion','full'},...
    'TrimmingOrderOptions',{'OrderPreference','score'});

rng(rngState);
[solutionSpaceBoxDisplacement,problemDataBoxDisplacement,iterDataBoxDisplacement] = sso_box_stochastic(designEvaluatorDisplacement,...
    initialDesign,designSpaceLowerBoundDisplacement,designSpaceUpperBoundDisplacement,optionsBox);
toc(timeElapsedBox)

timeElapsedBox = tic;
optionsBox = sso_stochastic_options('box',...
    'NumberSamplesPerIterationExploration',300,...
    'NumberSamplesPerIterationConsolidation',300,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',30,...
    'MaxIterConsolidation',30,...
    'UseAdaptiveGrowthRate',false,...
    'GrowthRate',0.05,...
    'ApplyLeanness','never',...
    'TrimmingOperationOptions',{'PassesCriterion','full'},...
    'TrimmingOrderOptions',{'OrderPreference','score'});

rng(rngState);
[solutionSpaceBoxMass,problemDataBoxMass,iterDataBoxMass] = sso_box_stochastic(designEvaluatorMass,...
    initialDesign,designSpaceLowerBoundMass,designSpaceUpperBoundMass,optionsBox);
toc(timeElapsedBox)


%% Component Opt
timeElapsedComponent = tic;
optionsComponent = sso_stochastic_options('component',...
    'NumberSamplesPerIterationExploration',300,...
    'NumberSamplesPerIterationConsolidation',300,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',30,...
    'MaxIterConsolidation',30,...
    'CandidateSpaceConstructorExploration',@CandidateSpaceDelaunay,...
    'CandidateSpaceConstructorConsolidation',@CandidateSpaceDelaunay,...
    'TrimmingMethodFunction',@component_trimming_method_corner_box_removal,...
    ... 'TrimmingMethodOptions',{'ReferenceDesigns','boundary-center'},...
    'UseAdaptiveGrowthRate',false,...
    'GrowthRate',0.2,...
    'ApplyLeanness','never',...
    'UsePaddingSamplesInTrimming',true,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'UsePreviousPaddingSamplesConsolidation',false,...
    'TrimmingOperationOptions',{'PassesCriterion','reduced'},...
    'TrimmingOrderOptions',{'OrderPreference','score'});

rng(rngState);
[componentSolutionSpaceDisplacement,problemDataComponentDisplacement,iterDataComponentDisplacement] = sso_component_stochastic(designEvaluatorDisplacement,...
    initialDesign,designSpaceLowerBoundDisplacement,designSpaceUpperBoundDisplacement,Components,optionsComponent);
toc(timeElapsedComponent)

timeElapsedComponent = tic;
optionsComponent = sso_stochastic_options('component',...
    'NumberSamplesPerIterationExploration',300,...
    'NumberSamplesPerIterationConsolidation',300,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',30,...
    'MaxIterConsolidation',30,...
    'CandidateSpaceConstructorExploration',@CandidateSpaceDelaunay,...
    'CandidateSpaceConstructorConsolidation',@CandidateSpaceDelaunay,...
    'TrimmingMethodFunction',@component_trimming_method_corner_box_removal,...
    ... 'TrimmingMethodOptions',{'ReferenceDesigns','boundary-center'},...
    'UseAdaptiveGrowthRate',false,...
    'GrowthRate',0.04,...
    'ApplyLeanness','never',...
    'UsePaddingSamplesInTrimming',true,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'UsePreviousPaddingSamplesConsolidation',false,...
    'TrimmingOperationOptions',{'PassesCriterion','reduced'},...
    'TrimmingOrderOptions',{'OrderPreference','score'});

rng(rngState);
[componentSolutionSpaceMass,problemDataComponentMass,iterDataComponentMass] = sso_component_stochastic(designEvaluatorMass,...
    initialDesign,designSpaceLowerBoundMass,designSpaceUpperBoundMass,Components,optionsComponent);
toc(timeElapsedComponent)


%% measure comparison
measureComponent1 = componentSolutionSpaceDisplacement(1).Measure;
measureComponent2 = componentSolutionSpaceDisplacement(2).Measure;
measureBox1 = prod(solutionSpaceBoxDisplacement(2,[1,2])-solutionSpaceBoxDisplacement(1,[1,2]));
measureBox2 = prod(solutionSpaceBoxDisplacement(2,[3,4])-solutionSpaceBoxDisplacement(1,[3,4]));
fprintf('\nVolume Increases - Node 1: %.3gx ; Node 2: %.gx\n',measureComponent1/measureBox1,measureComponent2/measureBox2);


%% Plot Visualization
% initial truss + component solution spaces
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement);
save_print_figure(gcf,[saveFolder,'InitialTrussComponent']);

% initial truss + component solution spaces + mass
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement,...
    'ComponentSolutionSpaceMass',componentSolutionSpaceMass);
save_print_figure(gcf,[saveFolder,'InitialTrussComponentWithMass']);

% initial truss + optimized truss + component solution spaces
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussComponent']);

% initial truss + optimized truss + component solution spaces + mass
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'NodePositionOptimalMass',nodePositionOptimalMass,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement,...
    'ComponentSolutionSpaceMass',componentSolutionSpaceMass);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussComponentWithMass']);

% initial truss + optimized truss + box solution space + component solution spaces
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'BoxSolutionSpaceDisplacement',solutionSpaceBoxDisplacement,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussBoxComponent']);

% initial truss + optimized truss + box solution space + component solution spaces + mass
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionOptimalDisplacement',nodePositionOptimalDisplacement,...
    'NodePositionOptimalMass',nodePositionOptimalMass,...
    'BoxSolutionSpaceDisplacement',solutionSpaceBoxDisplacement,...
    'BoxSolutionSpaceMass',solutionSpaceBoxMass,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement,...
    'ComponentSolutionSpaceMass',componentSolutionSpaceMass);
save_print_figure(gcf,[saveFolder,'InitialOptimizedTrussBoxComponentWithMass']);

% initial truss + box solution space + component solution spaces
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'BoxSolutionSpaceDisplacement',solutionSpaceBoxDisplacement,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement);
save_print_figure(gcf,[saveFolder,'InitialTrussBoxComponent']);

% initial truss + box solution space + component solution spaces + mass
plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'BoxSolutionSpaceDisplacement',solutionSpaceBoxDisplacement,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement,...
    'BoxSolutionSpaceMass',solutionSpaceBoxMass,...
    'ComponentSolutionSpaceMass',componentSolutionSpaceMass);
save_print_figure(gcf,[saveFolder,'InitialTrussBoxComponentWithMass']);

% initial truss + sample trusses + component solution space
nRandomTruss = 5;
randomTrussMovingNode = candidate_space_sampling_individual_feasible(componentSolutionSpaceDisplacement,Components,nRandomTruss);

plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,...
    'NodePositionInitial',initialDesign,...
    'NodePositionRandomDisplacement',randomTrussMovingNode,...
    'ComponentSolutionSpaceDisplacement',componentSolutionSpaceDisplacement);
save_print_figure(gcf,[saveFolder,'InitialRandomTrussComponent']);


%% plot candidate spaces samples
% candidate space 1
designSample = componentSolutionSpaceDisplacement(1).DesignSampleDefinition;
labelSample = componentSolutionSpaceDisplacement(1).IsInsideDefinition;
figure;
componentSolutionSpaceDisplacement(1).plot_candidate_space(gcf,'EdgeColor','none','FaceColor','g','FaceAlpha',0.5,'Linewidth',2.0);
hold all;
plot(designSample(labelSample,1),designSample(labelSample,2),'g.');
plot(designSample(~labelSample,1),designSample(~labelSample,2),'r.');
grid minor;
save_print_figure(gcf,[saveFolder,'ComponentSpace1TrimmingPlot']);

% candidate space 2
designSample = componentSolutionSpaceDisplacement(2).DesignSampleDefinition;
labelSample = componentSolutionSpaceDisplacement(2).IsInsideDefinition;
figure;
componentSolutionSpaceDisplacement(2).plot_candidate_space(gcf,'EdgeColor','none','FaceColor','g','FaceAlpha',0.5,'Linewidth',2.0);
hold all;
plot(designSample(labelSample,1),designSample(labelSample,2),'g.');
plot(designSample(~labelSample,1),designSample(~labelSample,2),'r.');
grid minor;
save_print_figure(gcf,[saveFolder,'ComponentSpace2TrimmingPlot']);


%% 
algoDataBox = postprocess_sso_box_stochastic(problemDataBoxDisplacement,iterDataBoxDisplacement);
plot_sso_box_stochastic_metrics(algoDataBox,'SaveFolder',saveFolder,'CloseFigureAfterSaving',true);

algoDataComponent = postprocess_sso_component_stochastic(problemDataComponentDisplacement,iterDataComponentDisplacement);
plot_sso_component_stochastic_metrics(algoDataComponent,'SaveFolder',saveFolder,'CloseFigureAfterSaving',true);



%% Save and Stop Transcripting
save([saveFolder,'Data.mat']);
diary off;


%% subfunction: plot truss
function figureHandle = plot_results_truss_six_bar_2d_two_moving_node(baseNode,nodeElement,varargin)
    parser = inputParser;
    parser.addParameter('NodePositionInitial',[]);
    parser.addParameter('NodePositionOptimalDisplacement',[]);
    parser.addParameter('NodePositionOptimalMass',[]);
    parser.addParameter('NodePositionRandomDisplacement',[]);
    parser.addParameter('NodePositionRandomMass',[]);
    parser.addParameter('DeformationInitial',[]);
    parser.addParameter('DeformationOptimalDisplacement',[]);
    parser.addParameter('DeformationOptimalMass',[]);
    parser.addParameter('BoxSolutionSpaceDisplacement',[]);
    parser.addParameter('ComponentSolutionSpaceDisplacement',[]);
    parser.addParameter('BoxSolutionSpaceMass',[]);
    parser.addParameter('ComponentSolutionSpaceMass',[]);
    parser.addParameter('IncludeWall',true);
    parser.addParameter('IncludeAppliedForce',false);
    parser.addParameter('IncludeAxesInformation',false);
    parser.addParameter('IncludeLegend',false);
    parser.addParameter('WallOptions',{});
    parser.addParameter('AppliedForceOptions',{});
    parser.addParameter('InitialTrussOptions',{});
    parser.addParameter('OptimalTrussDisplacementOptions',{});
    parser.addParameter('OptimalTrussMassOptions',{});
    parser.addParameter('RandomTrussDisplacementOptions',{});
    parser.addParameter('RandomTrussMassOptions',{});
    parser.addParameter('BoxSolutionSpaceDisplacementOptions',{});
    parser.addParameter('ComponentSolutionSpaceDisplacementOptions',{});
    parser.addParameter('BoxSolutionSpaceMassOptions',{});
    parser.addParameter('ComponentSolutionSpaceMassOptions',{});
    parser.addParameter('LegendOptions',{});
    parser.parse(varargin{:});
    options = parser.Results;

    wallX = [0 0];
    wallY = [-0.1 1.1];

    defaultInitialTrussOptions = {'ColorUndeformed',[0.8 0.8 0.8],'ColorDeformed','c','MaximumLinewidth',3.0,'DisplacementScaleFactor',500};
    [~,initialTrussOptions] = merge_name_value_pair_argument(defaultInitialTrussOptions,options.InitialTrussOptions);

    defaultOptimalTrussDisplacementOptions = {'ColorUndeformed','b','ColorDeformed','m','MaximumLinewidth',3.0,'DisplacementScaleFactor',500};
    [~,optimalTrussDisplacementOptions] = merge_name_value_pair_argument(defaultOptimalTrussDisplacementOptions,options.OptimalTrussDisplacementOptions);

    defaultOptimalTrussMassOptions = {'ColorUndeformed','y','ColorDeformed','k','MaximumLinewidth',3.0,'DisplacementScaleFactor',500};
    [~,optimalTrussMassOptions] = merge_name_value_pair_argument(defaultOptimalTrussMassOptions,options.OptimalTrussMassOptions);

    defaultRandomTrussDisplacementOptions = {'MaximumLinewidth',3.0};
    [~,randomTrussDisplacementOptions] = merge_name_value_pair_argument(defaultRandomTrussDisplacementOptions,options.RandomTrussDisplacementOptions);

    defaultRandomTrussMassOptions = {'MaximumLinewidth',3.0};
    [~,randomTrussMassOptions] = merge_name_value_pair_argument(defaultRandomTrussMassOptions,options.RandomTrussMassOptions);

    defaultWallOptions = {'Linewidth',8.0,'Color',[0.7 0.7 0.7]};
    [~,wallOptions] = merge_name_value_pair_argument(defaultWallOptions,options.WallOptions);

    defaultAppliedForceOptions = {'Color','r','LineWidth',3.0};
    [~,appliedForceOptions] = merge_name_value_pair_argument(defaultAppliedForceOptions,options.AppliedForceOptions);

    defaultBoxSolutionDisplacementOptions = {'EdgeColor','c','Linewidth',2.0};
    [~,boxSolutionDisplacementOptions] = merge_name_value_pair_argument(defaultBoxSolutionDisplacementOptions,options.BoxSolutionSpaceDisplacementOptions);

    defaultBoxSolutionMassOptions = {'EdgeColor',[0.9290 0.6940 0.1250],'Linewidth',2.0};
    [~,boxSolutionMassOptions] = merge_name_value_pair_argument(defaultBoxSolutionMassOptions,options.BoxSolutionSpaceMassOptions);

    defaultComponentSolutionDisplacementOptions = {'EdgeColor','g','FaceColor','none','FaceAlpha',0.5,'Linewidth',2.0};
    [~,componentSolutionDisplacementOptions] = merge_name_value_pair_argument(defaultComponentSolutionDisplacementOptions,options.ComponentSolutionSpaceDisplacementOptions);

    defaultComponentSolutionMassOptions = {'EdgeColor','k','FaceColor','none','FaceAlpha',0.5,'Linewidth',2.0};
    [~,componentSolutionMassOptions] = merge_name_value_pair_argument(defaultComponentSolutionMassOptions,options.ComponentSolutionSpaceMassOptions);

    defaultLegendOptions = {'location','west'};
    [~,legendOptions] = merge_name_value_pair_argument(defaultLegendOptions,options.LegendOptions);

    figureHandle = figure;
    hold all;
    
    % initial truss
    handleInitial = [];
    handleInitialDeformed = [];
    if(~isempty(options.NodePositionInitial))
        nodePositionInitial = baseNode;
        nodePositionInitial(2,:) = options.NodePositionInitial(:,[1,2]);
        nodePositionInitial(4,:) = options.NodePositionInitial(:,[3,4]);

        [handleInitial,handleInitialDeformed] = plot_truss_deformation(gcf,nodePositionInitial,nodeElement,options.DeformationInitial,initialTrussOptions{:});
    end

    % optimal truss  - displacement 
    handleOptimalDisplacement = [];
    handleOptimizedDisplacementDeformed = [];
    if(~isempty(options.NodePositionOptimalDisplacement))
        nodePositionOptimized = baseNode;
        nodePositionOptimized(2,:) = options.NodePositionOptimalDisplacement(:,[1,2]);
        nodePositionOptimized(4,:) = options.NodePositionOptimalDisplacement(:,[3,4]);

        [handleOptimalDisplacement,handleOptimizedDisplacementDeformed] = plot_truss_deformation(gcf,nodePositionOptimized,nodeElement,options.DeformationOptimalDisplacement,optimalTrussDisplacementOptions{:});
    end

    % optimal truss - mass 
    handleOptimalMass = [];
    handleOptimizedMassDeformed = [];
    if(~isempty(options.NodePositionOptimalMass))
        nodePositionOptimized = baseNode;
        nodePositionOptimized(2,:) = options.NodePositionOptimalMass(:,[1,2]);
        nodePositionOptimized(4,:) = options.NodePositionOptimalMass(:,[3,4]);

        [handleOptimalMass,handleOptimizedMassDeformed] = plot_truss_deformation(gcf,nodePositionOptimized,nodeElement,options.DeformationOptimalMass,optimalTrussMassOptions{:});
    end

    % box-shaped solution space  - displacement 
    handleToleranceNodeDisplacementBox = [];
    if(~isempty(options.BoxSolutionSpaceDisplacement))
        plot_design_box_2d(gcf,options.BoxSolutionSpaceDisplacement(:,[1,2]),boxSolutionDisplacementOptions{:});
        handleToleranceNodeDisplacementBox = plot_design_box_2d(gcf,options.BoxSolutionSpaceDisplacement(:,[3,4]),boxSolutionDisplacementOptions{:});
    end

    % box-shaped solution space - mass
    handleToleranceNodeMassBox = [];
    if(~isempty(options.BoxSolutionSpaceMass))
        plot_design_box_2d(gcf,options.BoxSolutionSpaceMass(:,[1,2]),boxSolutionMassOptions{:});
        handleToleranceNodeMassBox = plot_design_box_2d(gcf,options.BoxSolutionSpaceMass(:,[3,4]),boxSolutionMassOptions{:});
    end

    % component solution space - displacement
    handleToleranceNodeDisplacementComponent = [];
    if(~isempty(options.ComponentSolutionSpaceDisplacement))
        options.ComponentSolutionSpaceDisplacement(1).plot_candidate_space(gcf,componentSolutionDisplacementOptions{:});
        handleToleranceNodeDisplacementComponent = options.ComponentSolutionSpaceDisplacement(2).plot_candidate_space(gcf,componentSolutionDisplacementOptions{:});
    end

    % component solution space - mass
    handleToleranceNodeMassComponent = [];
    if(~isempty(options.ComponentSolutionSpaceMass))
        options.ComponentSolutionSpaceMass(1).plot_candidate_space(gcf,componentSolutionMassOptions{:});
        handleToleranceNodeMassComponent = options.ComponentSolutionSpaceMass(2).plot_candidate_space(gcf,componentSolutionMassOptions{:});
    end

    % random trusses - displacement
    handleRandomDisplacement = [];
    if(~isempty(options.NodePositionRandomDisplacement))
        nRandomTruss = size(options.NodePositionRandomDisplacement,1);
        trussColor = rand(nRandomTruss,3);
        for i=1:nRandomTruss
            randomNodePosition = baseNode;
            randomNodePosition(2,:) = options.NodePositionRandomDisplacement(i,[1,2]);
            randomNodePosition(4,:) = options.NodePositionRandomDisplacement(i,[3,4]);
            handleRandomDisplacement(i) = plot_truss_deformation(gcf,randomNodePosition,nodeElement,'ColorUndeformed',trussColor(i,:),randomTrussDisplacementOptions{:});
        end
    end

    % random trusses - mass
    handleRandomMass = [];
    if(~isempty(options.NodePositionRandomMass))
        nRandomTruss = size(options.NodePositionRandomMass,1);
        trussColor = rand(nRandomTruss,3);
        for i=1:nRandomTruss
            randomNodePosition = baseNode;
            randomNodePosition(2,:) = options.NodePositionRandomMass(i,[1,2]);
            randomNodePosition(4,:) = options.NodePositionRandomMass(i,[3,4]);
            handleRandomMass(i) = plot_truss_deformation(gcf,randomNodePosition,nodeElement,'ColorUndeformed',trussColor(i,:),randomTrussMassOptions{:});
        end
    end

    % wall
    handleWall = [];
    if(options.IncludeWall)
        handleWall = plot(wallX,wallY,wallOptions{:});
    end

    % applied force
    handleForce = [];
    if(options.IncludeAppliedForce)
        handleForce = quiver(2,0.5,0,-0.5,appliedForceOptions{:});
    end

    % axis
    grid minor;
    if(~options.IncludeAxesInformation)
        set(gca,'XColor', 'none','YColor','none');
    end

    % legend
    if(options.IncludeLegend)
        handleObjectAll = {...
            handleInitial,...
            handleInitialDeformed,...
            handleOptimalDisplacement,...
            handleOptimizedDisplacementDeformed,...
            handleOptimalMass,...
            handleOptimizedMassDeformed,...
            handleWall,...
            handleForce,...
            handleToleranceNodeDisplacementBox,...
            handleToleranceNodeDisplacementComponent,...
            handleToleranceNodeMassBox,...
            handleToleranceNodeMassComponent};

        legendTextAll = {...
            'Initial Truss',...
            'Initial Truss (Deformed)',...
            'Optimized Truss - Displacement',...
            'Optimized Truss (Deformed) - Displacement',...
            'Optimized Truss - Mass',...
            'Optimized Truss (Deformed) - Mass',...
            'Wall',...
            'Applied Force',...
            'Tolerance Region for the Node (Box) - Displacement',...
            'Tolerance Region for the Node (Component) - Displacement',...
            'Tolerance Region for the Node (Box) - Mass',...
            'Tolerance Region for the Node (Component) - Mass'};
        
        handleObject = [handleObjectAll{:}];
        legentText = {legendTextAll{~cellfun(@isempty,handleObjectAll)}};

        legend(handleObject,legentText,legendOptions{:});
    end

    if(nargout<1)
        clear figureHandle;
    end
end

