%% Cleanup
fclose all;
close all;
clear all;
clc;
more off;
diary off;


%% debugging
rng(4);


%% Documentation / Archive
rngState = rng;
saveFolder = save_diary_files(mfilename);
goldenRatio = (1+sqrt(5))/2;
figureSize = [goldenRatio 1]*8.5;


%% Considered material properties
% Material properties arrays
youngsModulusMaterial = [200e9, 70e9, 116e9, 45e9]; % [Pa] Steel, Aluminum, Titanium, Magnesium


%% system definition
systemFunction = @truss_two_bar_continuous_area_only;


%% design space definition
systemParameter = [1,1,45e9,45e9,1000];
nDivisions = 5;

minimumArea = 0.001;
maximumArea = 1;

nIter = 150;
nSample = 2000;
trimmingPasses = 'single';
trimmingOrder = 'lth';

performanceLowerLimitFactor = 0.9;
performanceUpperLimitFactor = 1.1;

evolutionIterationIndices = [];


%%
designSpaceLowerBound = [repmat(minimumArea,1,nDivisions),repmat(minimumArea,1,nDivisions)];
designSpaceUpperBound = [repmat(maximumArea,1,nDivisions),repmat(maximumArea,1,nDivisions)];
componentIndex = {[1:nDivisions],[nDivisions+1:2*nDivisions]};
initialDesign = mean([designSpaceLowerBound;designSpaceUpperBound],1);


%% compute initial design
bottomUpMapping = BottomUpMappingFunction(systemFunction,systemParameter);
performanceInitial = bottomUpMapping.response(initialDesign);

performanceLowerLimit = performanceLowerLimitFactor*performanceInitial;
performanceUpperLimit = performanceUpperLimitFactor*performanceInitial;


%% solution space computation
designEvaluator = DesignEvaluatorBottomUpMapping(...
    bottomUpMapping,...
    performanceLowerLimit,...
    performanceUpperLimit);

timeElapsedAlgorithmPlanar = tic;
optionsPlanar = sso_stochastic_options('component',...
    'NumberSamplesPerIterationExploration',nSample,...
    'NumberSamplesPerIterationConsolidation',nSample,...
    'SamplingMethodFunction',@sampling_random,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',nIter,...
    'MaxIterConsolidation',nIter,...
    'CandidateSpaceConstructor',@CandidateSpacePlanarTrimming,...
    'CandidateSpaceOptions',{'NormalizeGrowthDirection',true,'CheckRedundantTrimmingGrowth',false,'CheckRedundantTrimmingUpdate',true,'CheckDuplicatePointsGrowth',false,'CheckDuplicatePointsUpdate',true,'MeasureEstimationFactor',2},...
    'TrimmingMethodFunction',@component_trimming_method_planar_trimming,...
    'TrimmingMethodOptions',{'NormalizeVariables',true,'TrimmingSlack',1},...
    'GrowthRate',0.1^nDivisions,...
    'UseAdaptiveGrowthRate',true,...
    'TargetAcceptedRatioExploration',0.8,...
    'GrowthAdaptationFactorFunction',@growth_rate_adaptation_linear,...
    'ApplyLeanness','never',...
    'UsePaddingSamplesInTrimming',true,...
    'MaximumNumberPaddingSamples',10000,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'ShapeSamplesUsefulExploration',false,...
    'ShapeSamplesUsefulConsolidation',true,...
    'TrimmingOperationOptions',{'PassesCriterion',trimmingPasses},...
    'TrimmingOrderOptions',{'OrderPreference',trimmingOrder},...
    'LoggingLevel','all');
[componentSolutionSpacePlanar,optimizationDataPlanar] = sso_component_stochastic(designEvaluator,...
    initialDesign,designSpaceLowerBound,designSpaceUpperBound,componentIndex,optionsPlanar);
toc(timeElapsedAlgorithmPlanar)

timeElapsedAlgorithmCornerBox = tic;
optionsCornerBox = sso_stochastic_options('component',...
    'NumberSamplesPerIterationExploration',nSample,...
    'NumberSamplesPerIterationConsolidation',nSample,...
    'SamplingMethodFunction',@sampling_random,...
    'FixIterNumberExploration',true,...
    'FixIterNumberConsolidation',true,...
    'MaxIterExploration',nIter,...
    'MaxIterConsolidation',nIter,...
    'CandidateSpaceConstructor',@CandidateSpaceCornerBoxRemoval,...
    'CandidateSpaceOptions',{'NormalizeGrowthDirection',true,'CheckRedundantTrimmingGrowth',false,'CheckRedundantTrimmingUpdate',true,'CheckDuplicatePointsGrowth',false,'CheckDuplicatePointsUpdate',true,'MeasureEstimationFactor',2},...
    'TrimmingMethodFunction',@component_trimming_method_corner_box_removal,...
    'TrimmingMethodOptions',{'NormalizeVariables',true,'TrimmingSlack',1},...
    'GrowthRate',0.1^nDivisions,...
    'UseAdaptiveGrowthRate',true,...
    'TargetAcceptedRatioExploration',0.8,...
    'GrowthAdaptationFactorFunction',@growth_rate_adaptation_linear,...
    'ApplyLeanness','never',...
    'UsePaddingSamplesInTrimming',true,...
    'MaximumNumberPaddingSamples',10000,...
    'UsePreviousEvaluatedSamplesConsolidation',false,...
    'ShapeSamplesUsefulExploration',false,...
    'ShapeSamplesUsefulConsolidation',true,...
    'TrimmingOperationOptions',{'PassesCriterion',trimmingPasses},...
    'TrimmingOrderOptions',{'OrderPreference',trimmingOrder},...
    'LoggingLevel','all');
[componentSolutionSpaceCornerBox,optimizationDataCornerBox] = sso_component_stochastic(designEvaluator,...
    initialDesign,designSpaceLowerBound,designSpaceUpperBound,componentIndex,optionsCornerBox);
toc(timeElapsedAlgorithmCornerBox)


%% plot component solution spaces
nComponent = length(componentSolutionSpacePlanar);
for i=1:nComponent
    figure;
    componentSolutionSpacePlanar(i).plot_candidate_space(gcf,'FaceColor',color_palette_tol('cyan'),'EdgeColor',color_palette_tol('cyan'),'FaceAlpha',0.1);
    hold on;
    componentSolutionSpaceCornerBox(i).plot_candidate_space(gcf,'FaceColor',color_palette_tol('purple'),'EdgeColor','none','FaceAlpha',0.1);
    title(['Component ',num2str(i)]);
    legend('Planar Trimming','Corner Box Removal');
    save_print_figure(gcf,[saveFolder,'ComponentSolutionSpace',num2str(i)],'PrintFormat',{'png','pdf'});
end


%% plot results and metrics
% Individual results - Planar Trimming
resultsFolder = [saveFolder,'ResultsPlanarTrimming/'];
mkdir(resultsFolder);
algoDataPlanar = postprocess_sso_component_stochastic(optimizationDataPlanar);
plot_sso_component_stochastic_metrics(algoDataPlanar,...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});

% Individual results - Corner Box Removal
resultsFolder = [saveFolder,sprintf('ResultsCornerBoxRemoval/')];
mkdir(resultsFolder);
algoDataCornerBox = postprocess_sso_component_stochastic(optimizationDataCornerBox);
plot_sso_component_stochastic_metrics(algoDataCornerBox,...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});

% Comparison plots
resultsFolder = [saveFolder,'ResultsComparison/'];
mkdir(resultsFolder);
plot_sso_comparison_box_component_stochastic_metrics(...
    {},...  % No box data in this case
    {algoDataPlanar,algoDataCornerBox},...
    'ComponentLabel',{'Planar Trimming','Corner Box Removal'},...
    'ComponentColor',color_palette_tol({'cyan','purple'}),...
    'SaveFolder',resultsFolder,...
    'CloseFigureAfterSaving',true,...
    'SaveFigureOptions',{'Size',figureSize,'PrintFormat',{'png','pdf'}});


%% see component progress
initialPlotOptions = {'EdgeColor','none','FaceColor',color_palette_tol('blue'),'FaceAlpha',0.2};
grownPlotOptions = {'EdgeColor','none','FaceColor',color_palette_tol('green'),'FaceAlpha',0.2};
trimmedPlotOptions = {'EdgeColor','none','FaceColor',color_palette_tol('red'),'FaceAlpha',0.2};
plot_sso_component_evolution(optimizationDataCornerBox,...
    'InitialPlotOptions',initialPlotOptions,...
    'GrownPlotOptions',grownPlotOptions,...
    'TrimmedPlotOptions',trimmedPlotOptions,...
    'IterationIndices',evolutionIterationIndices);


%% Save and Stop Transcripting
save([saveFolder,'Data.mat'],'-v7.3');
diary off;

