function algoData = postprocess_active_learning_model_training(problemData,iterData)
%
%
%   Input:
%
%   Output:
%
%   See also .
%   
%   Copyright 2025 Eduardo Rodrigues Della Noce
%   SPDX-License-Identifier: Apache-2.0

%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
%   
%       http://www.apache.org/licenses/LICENSE-2.0
%   
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.

	% algorithm data
    iStart = 1;
    iEnd = length(iterData);

    % create column arrays
    nCandidateGenerated = [iterData.NumberGeneratedCandidates]';

    % 
    nIter = iEnd - iStart + 1;
    [nSample, nPositiveTraining, nNegativeTraining, ...
    	nFalsePositiveExploration,nFalseNegativeExploration,...
    	nTruePositiveExploration,nTrueFalseExploration,...
    	nFalsePositiveBoundary,nFalseNegativeBoundary,...
    	nTruePositiveBoundary,nTrueFalseBoundary,...
    	accuracyExploration,precisionExploration,recallExploration,...
    	specificityExploration,f1scoreExploration,...
    	accuracyBoundary,precisionBoundary,recallBoundary,...
    	specificityBoundary,f1scoreBoundary,...
        sampleSpaceMeasure,sampleSpaceGrownMeasure] = deal(nan(nIter,1));
    for i=iStart:iEnd
        nSample(i) = size(iterData(i).EvaluatedSamples,1);

        labelTrain = iterData(i).FastForwardModel.LabelTrain;
        nPositiveTraining(i) = sum(labelTrain); 
        nNegativeTraining(i) = sum(~labelTrain);

        nPredictedPositiveExploration(i) = sum(iterData(i).LabelPredicted(~iterData(i).SelectedBoundary));
    	nPredictedNegativeExploration(i) = sum(~iterData(i).LabelPredicted(~iterData(i).SelectedBoundary));

    	nEvaluatedPositiveExploration(i) = sum(iterData(i).LabelEvaluated(~iterData(i).SelectedBoundary));
    	nEvaluatedNegativeExploration(i) = sum(~iterData(i).LabelEvaluated(~iterData(i).SelectedBoundary));

    	nPredictedPositiveBoundary(i) = sum(iterData(i).LabelPredicted(iterData(i).SelectedBoundary));
    	nPredictedNegativeBoundary(i) = sum(~iterData(i).LabelPredicted(iterData(i).SelectedBoundary));

    	nEvaluatedPositiveBoundary(i) = sum(iterData(i).LabelEvaluated(iterData(i).SelectedBoundary));
    	nEvaluatedNegativeBoundary(i) = sum(~iterData(i).LabelEvaluated(iterData(i).SelectedBoundary));
    	
    	[falsePositiveExploration,falseNegativeExploration,truePositiveExploration,trueNegativeExploration] = ...
    		classification_confusion_matrix(...
            iterData(i).LabelEvaluated(~iterData(i).SelectedBoundary),...
    		iterData(i).LabelPredicted(~iterData(i).SelectedBoundary));
    	nFalsePositiveExploration(i) = sum(falsePositiveExploration);
    	nFalseNegativeExploration(i) = sum(falseNegativeExploration);
    	nTruePositiveExploration(i) = sum(truePositiveExploration);
    	nTrueFalseExploration(i) = sum(trueNegativeExploration);

    	[falsePositiveBoundary,falseNegativeBoundary,truePositiveBoundary,trueNegativeBoundary] = ...
    		classification_confusion_matrix(...
            iterData(i).LabelEvaluated(iterData(i).SelectedBoundary),...
    		iterData(i).LabelPredicted(iterData(i).SelectedBoundary));
    	nFalsePositiveBoundary(i) = sum(falsePositiveBoundary);
    	nFalseNegativeBoundary(i) = sum(falseNegativeBoundary);
    	nTruePositiveBoundary(i) = sum(truePositiveBoundary);
    	nTrueFalseBoundary(i) = sum(trueNegativeBoundary);

    	[accuracyExploration(i),precisionExploration(i),recallExploration(i),...
    		specificityExploration(i),f1scoreExploration(i)] = ...
    		classification_evaluation_metrics(falsePositiveExploration,...
    		falseNegativeExploration,truePositiveExploration,trueNegativeExploration);

    	[accuracyBoundary(i),precisionBoundary(i),recallBoundary(i),specificityBoundary(i),f1scoreBoundary(i)] = ...
    		classification_evaluation_metrics(falsePositiveBoundary,...
    		falseNegativeBoundary,truePositiveBoundary,trueNegativeBoundary);
    end

    % 
    trainingPositiveRatio = nPositiveTraining./(nNegativeTraining+nPositiveTraining);
    nPredictedPositive = nPredictedPositiveExploration + nPredictedPositiveBoundary;
    nPredictedNegative = nPredictedNegativeExploration + nPredictedNegativeBoundary;
    nEvaluatedPositive = nEvaluatedPositiveExploration + nEvaluatedPositiveBoundary;
    nEvaluatedNegative = nEvaluatedPositiveExploration + nEvaluatedPositiveBoundary;

    % wrap output
    algoData = struct(...
        'IndexStart',iStart,...
        'IndexEnd',iEnd,...
    	'NumberCandidatesGenerated',nCandidateGenerated,...
    	'NumberEvaluatedSamples',nSample,...
    	'NumberPositiveSamplesInTrainingDataset',nPositiveTraining,...
    	'NumberNegativeSamplesInTrainingDataset',nNegativeTraining,...
    	'NumberPredictedPositiveSamplesExploration',nPredictedPositiveExploration,...
    	'NumberPredictedNegativeSamplesExploration',nPredictedNegativeExploration,...
    	'NumberEvaluatedPositiveSamplesExploration',nEvaluatedPositiveExploration,...
    	'NumberEvaluatedNegativeSamplesExploration',nEvaluatedNegativeExploration,...
    	'NumberPredictedPositiveSamplesBoundary',nPredictedPositiveBoundary,...
    	'NumberPredictedNegativeSamplesBoundary',nPredictedNegativeBoundary,...
    	'NumberEvaluatedPositiveSamplesBoundary',nEvaluatedPositiveBoundary,...
    	'NumberEvaluatedNegativeSamplesBoundary',nEvaluatedNegativeBoundary,...
    	'NumberFalsePositiveExploration',nFalsePositiveExploration,...
    	'NumberFalseNegativeExploration',nFalseNegativeExploration,...
    	'NumberTruePositiveExploration',nTruePositiveExploration,...
    	'NumberTrueNegativeExploration',nTruePositiveExploration,...
    	'NumberFalsePositiveBoundary',nFalsePositiveBoundary,...
    	'NumberFalseNegativeBoundary',nFalseNegativeBoundary,...
    	'NumberTruePositiveBoundary',nTruePositiveBoundary,...
    	'NumberTrueNegativeBoundary',nTruePositiveBoundary,...
    	'AccuracyExploration',accuracyExploration,...
    	'PrecisionExploration',precisionExploration,...
    	'RecallExploration',recallExploration,...
    	'SpecificityExploration',specificityExploration,...
    	'F1scoreExploration',f1scoreExploration,...
    	'AccuracyBoundary',accuracyBoundary,...
    	'PrecisionBoundary',precisionBoundary,...
    	'RecallBoundary',recallBoundary,...
    	'SpecificityBoundary',specificityBoundary,...
    	'F1scoreBoundary',f1scoreBoundary,...
    	'TrainingDataPositiveRatio',trainingPositiveRatio,...
    	'NumberPredictedPositive',nPredictedPositive,...
    	'NumberPredictedNegative',nPredictedNegative,...
    	'NumberEvaluatedPositive',nEvaluatedPositive,...
    	'NumberEvaluatedNegative',nEvaluatedNegative);
end